// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4nLywzSyxZJpd6jbFkdlZByCC6XOiLIc',
    appId: '1:337842086344:web:649dcc4cde03b0b7e760fd',
    messagingSenderId: '337842086344',
    projectId: 'runo-moneymanager',
    authDomain: 'runo-moneymanager.firebaseapp.com',
    storageBucket: 'runo-moneymanager.firebasestorage.app',
    measurementId: 'G-5B6PQGL016',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp0sIgYjusyFAd_QtWXgS_uqmKqIwCR3s',
    appId: '1:337842086344:android:0eda6c47b6ecf1e1e760fd',
    messagingSenderId: '337842086344',
    projectId: 'runo-moneymanager',
    storageBucket: 'runo-moneymanager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAslEMzrvogCVfQDgKM_3V8-bfFOwfy3UU',
    appId: '1:337842086344:ios:3cf68cfbf6cc9008e760fd',
    messagingSenderId: '337842086344',
    projectId: 'runo-moneymanager',
    storageBucket: 'runo-moneymanager.firebasestorage.app',
    androidClientId:
        '337842086344-1rf4g46e7m1ufn14d2frssbdvrli6ivk.apps.googleusercontent.com',
    iosClientId:
        '337842086344-jutrbvglcgu2kk6mpgsattarq3nvilul.apps.googleusercontent.com',
    iosBundleId: 'ai.runo.moneymanager',
  );
}
